sudo: required
dist: trusty

language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update

install:
- sudo apt-get install g++-4.8 libjemalloc-dev valgrind
- export CXX="g++-4.8"

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug .. && make
  - valgrind --leak-check=yes ./test/test_driver
